import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { Map } from '@wprdc-components/basic-map';

const Home: NextPage = () => {
  // set up map menu for neighborhoods
  // make api endpoint for menu layers to fill in data for type GeogLevel
  //  refactor GeogLevel since we don't need all that carto crap, we can use our own
  //  tile server now
  // have map not show layer panel if no options
  // setup special taxonomy to limit indicators for this ap

  return (
    <div className={styles.wrapper}>
      <Head>
        <title>REACH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.intro}>
          <div className={styles.title}>REACH/SSPGH</div>
          <div className={styles.subtitle}>Indicators of some sort</div>
          <p className={styles.description}>
            Grandis visus satis manifestums brabeuta est. Candidatus de emeritis
            gluten, prensionem accentor! Est castus decor, cesaris. Liberi de
            audax devirginato, attrahendam classis! Neuter spatii nunquam locuss
            gluten est. Ubi est peritus galatae.
          </p>
          <p className={styles.description}>
            Cum ignigena mori, omnes mineralises transferre brevis, fortis
            coordinataees. Festus, noster detriuss acceleratrix acquirere de
            germanus, flavum sectam. Cum demissio volare, omnes classises amor
            noster, superbus hilotaees. Barbatus, altus mineraliss unus
            prensionem de albus, pius luba.
          </p>
        </div>
        <div className={styles.mapSection}>MAP WILL GO HERE</div>
      </div>
      <div className={styles.details}>
        <div className={styles.geoDetails}>
          <div className={styles.geogTitle}>Communityville</div>
        </div>
        <div className={styles.contextDetails}>
          Pius, noster assimilatios mechanice demitto de salvus, audax cannabis.
          Cum messor mori, omnes compateres imperium grandis, gratis indexes.
          Cum tabes potus, omnes candidatuses demitto germanus, brevis
          brabeutaes. Lapsuss sunt musas de barbatus amor.
        </div>
      </div>
      <div className={styles.dashboard}>
        <div className={styles.domainSection}>
          <div className={styles.domainTitle}></div>
        </div>
        <div className={styles.domainSection}></div>
        <div className={styles.domainSection}></div>
      </div>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
